Project 
================
Mary Brown
10/5/2021  

## Project One Discussion  
  For this particular project I wanted to use data that was easy to pull from the API to make my functions. I first went through and reviewed all of the API links and decided that it was probably best to work with the COVID API. There was a lot of data within this API that seemed very comparable, especially for the graphs/plots portion of this project. One piece of interesting data was being able to compare the amount of deaths in different countries. For example, my bar plot shows the amount of deaths by chosen country codes. Out of the countries shown on my bar plot, Argentina seems to have more total deaths compared to Afganistan, Australia, etc. I created two boxplots to show the active cases in the United States vs. the active cases in South Africa which also showed interesting results. South Africa seems to have more active cases when compared to the United States which makes me wonder if this is partially due to resources.  
  The most difficult part of the project for me was creating our functions. Functions in R have always been difficult to me and I'm not sure why, I think because they can take in so much data and it starts to run together for me. I spent a whole day just re-reading the data within endpoints as well as the project instructions just to wrap my head around the concept and how I needed to set up those functions. This project definitely isn't my best work but I do feel like I'm learning a lot so it is beneficial for me. For future projects, I plan to allow myself more time to just digest what it is that we are actually trying to figure out. I would also probably explore more of the data prior to choosing what endpoints to work with. It actually became easier to create functions after I created graphs with the data because then I understood better what endpoints I was going to need for the summary data. 

```{r, echo=FALSE}
library(rmarkdown)
rmarkdown::render("~/Desktop/R Programming/git-project/Project-1-558/Project-1-558/2021-10-4-Project-Blog-Post.Rmd",
                  output_format = "github_document",
                  output_dir = "../_posts/",
                  output_options = list(html_preview=FALSE, keep_html=FALSE)
                  )  
```